CREATE TABLE pagamentos
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value              DECIMAL                                 NOT NULL,
    name               VARCHAR(100),
    number             VARCHAR(19),
    expiration         VARCHAR(7),
    code               VARCHAR(3),
    status             INTEGER                                 NOT NULL,
    order_id           BIGINT                                  NOT NULL,
    form_of_payment_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_pagamentos PRIMARY KEY (id)
);